# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

duckdns:
  domain: thedavieshome
  access_token: !secret duckdns_token

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

anniversaries:
  sensors:
    - name: Adelaide Half Marathon
      date: "2023-08-27"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
