# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

duckdns:
  domain: thedavieshome
  access_token: !secret duckdns_token

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

anniversaries:
  sensors:
    - name: Claire Half April 2024
      date: "2024-04-07"
    - name: Barossa Half May 2024
      date: "2024-05-26"
    - name: Gold Coast Half July 2024
      date: "2024-07-06"
    - name: Adelaide Half August 2024
      date: "2024-08-25"
    - name: McLaren Vale Half October 2024
      date: "2024-10-20"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
